/*配置文件                                                                                                                                                                                                             
* //服务端口号                                                                                                                                                                                                          
* //mysql 地址                                                                                                                                                                                                       
* //mysql 端口                                                                                                                                                                                                       
* //redis地址                                                                                                                                                                                                        
* //redis端口号                                                                                                                                                                                                       
*/                                                                                                                                                                                                                 
var development_env ={                                                                                                                                                                                             
    port: 8082,                                                                                                                                                                                                    
    mysql_host:'127.0.0.1',                                                                                                                                                                                        
    mysql_port:'3386',                                                                                                                                                                                             
    redis_host:'127.0.0.1',                                                                                                                                                                                        
    redis_port: '4001',                                                                                                                                                                                            
    pixivConfig:{                                                                                                                                                                                                  
        form :{                                                                                                                                                                                                    
            pixiv_id:'',                                                                                                                                                                           
            password:'',                                                                                                                                                                             
            captcha:  "",                                                                                                                                                                                          
            g_recaptcha_response:"",                                                                                                                                                                               
            post_key: "",                                                                                                                                                                                          
            source: "pc"                                                                                                                                                                                           
        },                                                                                                                                                                                                         
        headers:{                                                                                                                                                                                                  
            'Referer':"http://www.pixiv.net",                                                                                                                                                                      
            'User-Agent':"Mozilla/5.0 (Windows NT 6.3; rv:27.0) Gecko/20100101 Firefox/27.0",                                                                                                                      
        },                                                                                                                                                                                                         
        cookieAbout:{                                                                                                                                                                                              
            path:'.cookie',                                                                                                                                                                                        
            cookies:null                                                                                                                                                                                           
        }                                                                                                                                                                                                          
    },                                                                                                                                                                                                             
    pathConfig:{                                                                                                                                                                                                   
        webPath:'./client',                                                                                                                                                                                        
        downloadPath:'./client/download/'                                                                                                                                                                          
    }                                                                                                                                                                                                              

}                                                                                                                                                                                                                  
                                                                                                                                                                                                                   
                                                                                                                                                                                                                   
module.exports = development_env                                                                                                                                                                                   
